### ISSUE TITLE
how to attrubte the author in citation?

### ISSUE THREAD

**Issue by epogrebnyak** [thma/WhyHaskellMatters#6]
@thma, Many tanks for the article!

I would like to make a reference to _WhyHaskellMatters_, but in doubt about proper citation - could not find your name on the page or around. How should I cite? As of now I got itr as below but it does not sound specific enough:

- [Why Haskell Matters](https://github.com/thma/WhyHaskellMatters) by [@thma](https://github.com/thma)

**Comment by thma** [comment]
Hi Evgeny,

Thanks for your kind words!

My full name is Thomas Mahler. 
I've also updated my github profile to display my full name.

best,
Thomas

**Comment by epogrebnyak** [comment]
Thank you! Added the link to our collection of Haskell learning resources.

**Comment by thma** [comment]
That's a nice list of learning material!
For people with a background in OO programming I've written a larger study that relates software design patterns to Haskell type classes: https://github.com/thma/LtuPatternFactory.

Maybe it's useful for your list of resources as well.

**Comment by epogrebnyak** [comment]
Thank you @thma - the article takes a reader beyond "SOLID is just funсtions" and gives extra useful motivation to look Typeclassopedia. Added to the list!

**Comment by epogrebnyak** [comment]
Alos noticed some short discussion [here](http://blog.ezyang.com/2010/05/design-patterns-in-haskel/), much more brief and somewhat different (eg take on singletons)

**Comment by thma** [comment]
Yes, I've read that blog entry. My approach was a bit different, I was starting with the type classes mentioned in Typeclassopedia and tried to relate them to OO patterns.
I've not tried to mapp all GOF patterns to something in the FP world.
I was fascinated how software patterns relate to mathematical concepts from abstract algebra. (See my conclusion section)

Thanks for adding my study to your list!

**Comment by epogrebnyak** [comment]
> Thanks for adding my study to your list!

My pleasure! At my level I'm always exited to see new angles/approaches to Haskell topics, and it is on my own reading list. At some point the type class system should click and become one's friend.

(For [my own refererence](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system) - suprisingly approachable wikipedia article)
